name: "Testing and release preparation"

on:
  push:
    branches: [ master, dev ]
    tags: [ "v*" ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build-and-test:
    name: "Build and test"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "Install libpam"
      run: sudo apt-get install -y libpam-dev
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.7
    - name: "Verify build.sh"
      run: |
        ./build.sh
        ./build.sh --destdir destdir/ install
        find destdir/
    - name: "Unit & module tests"
      run: |
        go test ./... -coverprofile=coverage.out -covermode=atomic
    - name: "Integration tests"
      run: |
        cd tests/
        ./run.sh
    - uses: codecov/codecov-action@v2
      with:
        files: ./coverage.out
        flags: unit
    - uses: codecov/codecov-action@v2
      with:
        files: ./tests/coverage.out
        flags: integration
  artifact-builder:
    name: "Prepare release artifacts"
    needs: build-and-test
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    container:
      image: "alpine:edge"
    steps:
      - uses: actions/checkout@v1 # v2 does not work with containers
      - name: "Install build dependencies"
        run: |
          apk add --no-cache gcc go
      - name: "Create and package build tree"
        run: |
          ./build.sh --static build
          ./build.sh --destdir ~/package-output/ install
          mv ~/package-output/ ~/maddy-$(cat .version)-x86_64-linux-musl
          pushd ~
          tar c ./maddy-$(cat .version)-x86_64-linux-musl | zstd > ~/maddy-x86_64-linux-musl.tar.zst
          popd
      - name: "Save source tree"
        run: |
          rm -rf .git
          cp -r . ~/maddy-$(cat .version)-src
          pushd ~
          tar c ./maddy-$(cat .version)-src | zstd > ~/maddy-src.tar.zst
          popd
      - name: "Upload source tree"
        uses: actions/upload-artifact@v2
        with:
          name: maddy-src.tar.zst
          path: '~/maddy-src.tar.zst'
          if-no-files-found: error
      - name: "Upload binary tree"
        uses: actions/upload-artifact@v2
        with:
          name: maddy-binary.tar.zst
          path: '~/maddy-x86_64-linux-musl.tar.zst'
          if-no-files-found: error
  docker-builder:
    name: "Build Docker image"
    needs: build-and-test
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: "ghcr.io"
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            foxcpp/maddy:${{ github.ref_name }}
            ghcr.io/foxcpp/maddy:${{ github.ref_name }}

